### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by hei-** [ckeyer/beewechat#1]
1、$ bee run
         ...
        beewechat/main.go:7:2: import "github.com/ckeyer/beewechat/wechat": cannot find package
        2015/05/11 06:47:37 [ERRO] ============== Build failed ===================

2、$ go get github.com/ckeyer/beewechat/wechat
package github.com/ckeyer/beewechat/wechat
    imports apibaiwandun/models/global: unrecognized import path "apibaiwandun/models/global"
package github.com/ckeyer/beewechat/wechat
    imports apibaiwandun/weichat/msg: unrecognized import path "apibaiwandun/weichat/msg"
package github.com/ckeyer/beewechat/wechat
    imports funxdata/models/global: unrecognized import path "funxdata/models/global"

**Comment by ckeyer** [comment]
本来准备改下结构的,结构没改完,然后搁置了,这几天弄下

**Comment by ckeyer** [comment]
已解决
